# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42dbd0fd1c7857c0d6e1334e6a71f738a01876658fc0c819ede998911a93659bd09eb31f519e32c36da5c51baa38708a469429a2235956eaff3f257d17a1f101

test:
  secret_key_base: 2e08f5f049235d747dcedaefe89e595a331513fba208688c64a092317533bfc049f805656dbfd776078a6aa98b691f79afc3918ee7e7f56c4a9e83464757488a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
